### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by dmatora** [avarayr/suaveui#8]

**Comment by avarayr** [comment]
Thanks for raising this issue. Notifications are still work in progress

**Comment by dmatora** [comment]
Are they missing proper configuration or just not supposed to be working yet?

**Comment by avarayr** [comment]
> Are they missing proper configuration or just not supposed to be working yet?

The bulk of the actual logic behind notifications is done, i just need to tie it all together. I'm working on it right now!

**Comment by avarayr** [comment]
@dmatora I've updated the repo with several changes. You should be able to pull the pre-build docker image following the instructions.

Notifications should be working now. Check out the new GIF demo in the README

**Comment by dmatora** [comment]
Hey, great job! I've never seen 1 click ClaudFlare forwarding setup before.
And now when I click test notification I can see one (in Chrome it even works on localhost, on iPhone it works via PWA)
But I don't get notifications when AI finishes generating message, so it's still not really working :)

**Comment by dmatora** [comment]
Saw process.env.VERCEL_URL in the code and decided to try deploying it to vercel.
Deployment went find, but app is not working.
UI loads but fails calling backend.
/api/trpc/chat.all throws http 500
```
___          ______                
    / _ \         | ___ \               
   / /_\ \ ___ ___| |_/ / __ _ ___  ___ 
   |  _  |/ __/ _ \ ___ \/ _` / __|/ _ \
   | | | | (_|  __/ |_/ / (_| \__ \  __/
   \_| |_/\___\___\____/ \__,_|___/\___|
realtime database
Unhandled Rejection: [Error: EROFS: read-only file system, mkdir './suaveui.acebase'] {
  errno: -30,
  code: 'EROFS',
  syscall: 'mkdir',
  path: './suaveui.acebase'
}
Unhandled rejection: [Error: EROFS: read-only file system, mkdir './suaveui.acebase'] {
errno: -30,
code: 'EROFS',
syscall: 'mkdir',
path: './suaveui.acebase'
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

**Comment by dmatora** [comment]
I saw `  body: 'the VAPID credentials in the authorization header do not correspond to the credentials used to create the subscriptions.\n',` in the logs and figured what the issue was. Database had old subscription. I removed data.db from suaveui.acebase, restarted app and configured it from scratch and notifications are finally working!

**Comment by dmatora** [comment]
Well, maybe not working so well.
Current solution wouldn't work without internet connection, right?

**Comment by avarayr** [comment]
> I saw ` body: 'the VAPID credentials in the authorization header do not correspond to the credentials used to create the subscriptions.\n',` in the logs and figured what the issue was. Database had old subscription. I removed data.db from suaveui.acebase, restarted app and configured it from scratch and notifications are finally working!

Ah, great catch. Btw, you won't see notifications from chats while the chat screen is visible on the screen. It's intended mostly for slow generations, for example using a 200B model with very low token per second, and you get a notification when the message is finished.

Yes, notifications will not work offline. This is a core limitation of how Push notifications work.

Basically, your device opens a passive keep-alive socket to Google/Apple push server, and it listens for new data. To my knowledge there's no way to self host the push server.

We were blessed to have VAPID standard to break away from Google/apple walled garden around push notifications, since originally push notifications from apps that were not blessed by Google/Apple was impossible.

**Comment by avarayr** [comment]
@dmatora Yes in theory that will work, but here's the challenge. We want the user to be able to close/minimize the app (on their iPhone) and do other things while the slow generation is happening. 

Using your approach, we need to make sure that while the app is in background, the JavaScript is still being executed to periodically check whether we received the full response from the backend.

I'm afraid Android/iPhone decide to suspend apps while they're in the background, so we won't be able to check whether the generation has finished, and therefore we won't be able to send the client-side notification.

**Comment by dmatora** [comment]
it would at least work on desktop, where I mainly chat with ai anyway

**Comment by avarayr** [comment]
> it would at least work on desktop, where I mainly chat with ai anyway

Good point. I'll have to figure out how to give the user a choice between fully offline client side notifications, and push notifications using Google/Apple servers.

**Comment by dmatora** [comment]
one way would be to check if client is a desktop

**Comment by dmatora** [comment]
I would still check how background js throttling affects it

**Comment by dmatora** [comment]
Would be nice to be able to serve over https with self signed certificate, something like
```
const https = require('https');
const selfsigned = require('selfsigned');

const attrs = [{ name: 'commonName', value: 'localhost' }];
const pems = selfsigned.generate(attrs, { days: 365 });

const server = https.createServer({
  key: pems.private,
  cert: pems.cert
}, (req, res) => {
  res.writeHead(200);
  res.end('Hello, HTTPS world!');
});

server.listen(443, () => {
  console.log('HTTPS server running on port 443');
});
```
this make running offline server so much easier

**Comment by avarayr** [comment]
> Would be nice to be able to serve over https with self signed certificate, something like
> 
> ```
> const https = require('https');
> const selfsigned = require('selfsigned');
> 
> const attrs = [{ name: 'commonName', value: 'localhost' }];
> const pems = selfsigned.generate(attrs, { days: 365 });
> 
> const server = https.createServer({
>   key: pems.private,
>   cert: pems.cert
> }, (req, res) => {
>   res.writeHead(200);
>   res.end('Hello, HTTPS world!');
> });
> 
> server.listen(443, () => {
>   console.log('HTTPS server running on port 443');
> });
> ```
> 
> this make running offline server so much easier

Ah nice.. I'm currently use hono to serve the backend (src/server/hono.ts) 

I'll see how I can integrate self signed to make a seamless https connection.

**Comment by avarayr** [comment]
Just from preliminary research, it looks like PWA/Service worker might not work using self signed certificates.

**Comment by dmatora** [comment]
Well it does have issues. In safari PWA won't load. In Chrome when I launch PWA I have to approve certificate each time, which redirects me from app to Chrome, and once approved I have to click open in app to move it back. It's messy but I can't think of other solution for working offline.

**Comment by dmatora** [comment]
Well, at some point I got tired of reapproving certificate and issued let's encrypt certificate for personal domain pointing to local network Ip, got it validated via dns txt entry and got nginx reverse proxy running, pointing to local network running suaveui instance

**Comment by avarayr** [comment]
> Well, at some point I got tired of reapproving self issued certificate and issued let's encrypt certificate for personal domain pointing to local network Ip, got it validated via dns txt entry and got nginx reverse proxy running, pointing to local network running suaveui instance

Nice! I suggest to look into setting up Tailscale and pointing your domain to the local Tailscale address to have private access to your instance when not connected to your home network.
